---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
spec:
  ClusterIP: None
  ports:
  - port: 9092
    name: kafka
  selector:
    app: kafka
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka"
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wrap/kfkb:3.0
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 2181
          name: zookeeper
        volumeMounts:
        - name: configmap-volume
          mountPath: /opt/server.properties
      volumes:
      - name: configmap-volume
        configMap:
          name: kafka-configmap
