apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-headless
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Chart.Name }}
spec:
  clusterIP: None
  ports:
    - port: 9092
      name: kafka
    - port: 2181
      name: zkp-client
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
