apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: 9092
      name: kafka
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
